-- Canonical JSON file format and cleanup of PUBLIC duplicate.
USE DATABASE EVO_DEMO;

-- Remove duplicate in PUBLIC to avoid ambiguity.
DROP FILE FORMAT IF EXISTS PUBLIC.IOWA_JSON_FORMAT;

USE SCHEMA IOWA_LIQUOR_SALES;

CREATE OR REPLACE FILE FORMAT IOWA_JSON_FORMAT
  TYPE = JSON
  COMPRESSION = AUTO
  ENABLE_OCTAL = FALSE
  ALLOW_DUPLICATE = FALSE
  STRIP_OUTER_ARRAY = FALSE
  STRIP_NULL_VALUES = FALSE
  IGNORE_UTF8_ERRORS = FALSE
  REPLACE_INVALID_CHARACTERS = FALSE
  SKIP_BYTE_ORDER_MARK = TRUE
  MULTI_LINE = TRUE
  BINARY_FORMAT = HEX
  DATE_FORMAT = AUTO
  TIME_FORMAT = AUTO
  TIMESTAMP_FORMAT = AUTO;
