-- Network rule and external access integration for Socrata API
USE DATABASE EVO_DEMO;
USE SCHEMA IOWA_LIQUOR_SALES;
USE WAREHOUSE IOWA_WH;

CREATE OR REPLACE NETWORK RULE IOWA_HTTP_RULE
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST = ('data.iowa.gov:443');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION IOWA_HTTP_INT
  ALLOWED_NETWORK_RULES = (IOWA_HTTP_RULE)
  ENABLED = TRUE;
