-- Environment setup: DB, schema, warehouse, stage, file format, raw + silver tables
CREATE DATABASE IF NOT EXISTS EVO_DEMO;
USE DATABASE EVO_DEMO;

CREATE SCHEMA IF NOT EXISTS IOWA_LIQUOR_SALES;
USE SCHEMA IOWA_LIQUOR_SALES;

CREATE WAREHOUSE IF NOT EXISTS IOWA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE STAGE IF NOT EXISTS IOWA_LIQUOR_SALES.RAW_STAGE;

CREATE OR REPLACE TABLE IOWA_LIQUOR_SALES.RAW_IOWA (
  RAW VARIANT,
  FILE_NAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM IOWA_LIQUOR_SALES.RAW_IOWA_STREAM
  ON TABLE IOWA_LIQUOR_SALES.RAW_IOWA
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TABLE IOWA_LIQUOR_SALES.IOWA_LIQUOR_SALES (
  INVOICE_AND_ITEM_NUMBER STRING,
  SALE_DATE DATE,
  SALE_YEAR INT,
  SALE_MONTH INT,
  STORE_NUMBER INT,
  STORE_NAME STRING,
  ADDRESS STRING,
  CITY STRING,
  ZIP_CODE STRING,
  STORE_LOCATION VARIANT,
  COUNTY_NUMBER INT,
  COUNTY STRING,
  CATEGORY INT,
  CATEGORY_NAME STRING,
  LIQUOR_CATEGORY STRING,
  VENDOR_NUMBER INT,
  VENDOR_NAME STRING,
  ITEM_NUMBER INT,
  ITEM_DESCRIPTION STRING,
  PACK INT,
  BOTTLE_VOLUME_ML INT,
  STATE_BOTTLE_COST DOUBLE,
  STATE_BOTTLE_RETAIL DOUBLE,
  BOTTLES_SOLD INT,
  SALE_DOLLARS DOUBLE,
  VOLUME_SOLD_LITERS DOUBLE,
  VOLUME_SOLD_GALLONS DOUBLE
);
