USE DATABASE EVO_DEMO;
USE SCHEMA IOWA_LIQUOR_SALES;

-- Streamlit home
CREATE DATABASE IF NOT EXISTS IOWA_STREAMLIT;
CREATE SCHEMA IF NOT EXISTS IOWA_STREAMLIT.PUBLIC;

-- Compute pool for Streamlit
CREATE COMPUTE POOL IF NOT EXISTS IOWA_STREAMLIT_POOL
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = CPU_X64_XS;

-- Warehouse for Streamlit queries
CREATE WAREHOUSE IF NOT EXISTS IOWA_STREAMLIT_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- Grants (adjust role as needed)
GRANT USAGE ON DATABASE IOWA_STREAMLIT TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA IOWA_STREAMLIT.PUBLIC TO ROLE PUBLIC;
GRANT CREATE STREAMLIT ON SCHEMA IOWA_STREAMLIT.PUBLIC TO ROLE PUBLIC;
GRANT CREATE STAGE ON SCHEMA IOWA_STREAMLIT.PUBLIC TO ROLE PUBLIC;
GRANT USAGE ON COMPUTE POOL IOWA_STREAMLIT_POOL TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE IOWA_STREAMLIT_WH TO ROLE PUBLIC;

-- Data access for the app (adjust role as needed)
GRANT USAGE ON DATABASE EVO_DEMO TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA EVO_DEMO.IOWA_LIQUOR_SALES TO ROLE PUBLIC;
GRANT SELECT ON TABLE EVO_DEMO.IOWA_LIQUOR_SALES.IOWA_LIQUOR_SALES TO ROLE PUBLIC;

-- Notes:
-- - Point your Streamlit app to IOWA_STREAMLIT.PUBLIC.
-- - Reference data from EVO_DEMO.IOWA_LIQUOR_SALES (use IOWA_STREAMLIT_WH or IOWA_WH).
