USE DATABASE EVO_DEMO;
USE SCHEMA IOWA_LIQUOR_SALES;
USE WAREHOUSE IOWA_WH;

-- Inspect the stage
LIST @IOWA_LIQUOR_SALES.RAW_STAGE/iowa;

-- File format for JSON lines
CREATE OR REPLACE FILE FORMAT IOWA_JSON_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

-- Landing table for the test
CREATE OR REPLACE TABLE TEST_STAGE_LOAD (
  RAW VARIANT,
  FILE_NAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Copy staged JSONL files into the table
COPY INTO TEST_STAGE_LOAD (RAW, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @IOWA_LIQUOR_SALES.RAW_STAGE/iowa
)
FILE_FORMAT = (FORMAT_NAME = IOWA_JSON_FORMAT)
PATTERN = '.*\\.jsonl';

-- Verify
SELECT COUNT(*) AS ROWS_LOADED FROM TEST_STAGE_LOAD;
SELECT * FROM TEST_STAGE_LOAD LIMIT 5;
