USE DATABASE EVO_DEMO;
USE SCHEMA IOWA_LIQUOR_SALES;
USE WAREHOUSE IOWA_WH;

-- Inspect the stage (non-destructive)
LIST @IOWA_LIQUOR_SALES.RAW_STAGE/iowa;

-- Temporary landing table for a spot-check
CREATE OR REPLACE TEMP TABLE TEST_STAGE_LOAD (
  RAW VARIANT,
  FILE_NAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Copy staged JSONL files into the temp table using the canonical format
COPY INTO TEST_STAGE_LOAD (RAW, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @IOWA_LIQUOR_SALES.RAW_STAGE/iowa
)
FILE_FORMAT = (FORMAT_NAME = EVO_DEMO.IOWA_LIQUOR_SALES.IOWA_JSON_FORMAT)
PATTERN = '.*\\.jsonl'
ON_ERROR = 'CONTINUE';

-- Verify a small sample
SELECT COUNT(*) AS rows_loaded FROM TEST_STAGE_LOAD;
SELECT * FROM TEST_STAGE_LOAD LIMIT 5;
