USE DATABASE EVO_DEMO;
USE SCHEMA IOWA_LIQUOR_SALES;

CREATE OR REPLACE TASK WEEKLY_IOWA_LOAD
  WAREHOUSE = IOWA_WH
  SCHEDULE = 'USING CRON 0 2 * * MON UTC'
AS
  CALL EVO_DEMO.IOWA_LIQUOR_SALES.SP_LOAD_IOWA_LATEST();

ALTER TASK WEEKLY_IOWA_LOAD RESUME;
